name: 'Wait for Workflow Completion'
description: 'Action to wait for the completion of a workflow'
runs:
    using: 'node20'
    main: 'dist/index.js'
inputs:
    GITHUB_TOKEN:
        description: 'GitHub token'
        required: true
    REPOSITORY:
        description: 'repository name'
        required: true
    WORKFLOW_NAME:
        description: 'workflow name to dispatch'
        required: true
    CLIENT_PAYLOAD:
     description: 'JSON payload for the dispatched workflow: preview url, etc. `{"preview_url": "https://vercel-preiview-example.com"}`'
     required: true
    VERIFY_JOB: 
     description: 'Wait for dispatch to complete, on by default, set to false to skip'
     required: false
