name: 'Dispatch a workflow and wait for completion'
description: 'Action to dispatch and wait for or skip the completion of a workflow'
runs:
    using: 'node20'
    main: 'dist/index.js'
inputs:
    GITHUB_TOKEN:
        description: 'GitHub token'
        required: true
    REPOSITORY:
        description: 'repository name'
        required: true
    WORKFLOW_NAME:
        description: 'workflow name to dispatch'
        required: true
    CLIENT_PAYLOAD:
     description: 'JSON payload for the dispatched workflow: preview url, etc. `{"preview_url": "https://vercel-preiview-example.com"}`'
     required: false
    VERIFY_JOB: 
     description: 'Wait for dispatch to complete, off by default, set to true to wait for the job to complete'
     required: false
